### ISSUE TITLE
Deprecation warning when using "Apply a label to an issue" example from README

### ISSUE THREAD

**Issue by DilumAluthge** [actions/github-script#14]
When I use the "Apply a label to an issue" example from the README, I get the following deprecation warning. I am using `actions/github-script@0.3.0`.

```
Run actions/github-script@0.3.0
2
  with:
3
    github-token: ***
4
    script: github.issues.addLabels({...context.issue, labels: ['needs version bump']})
5
  
6
    debug: false
7
    user-agent: actions/github-script
8
Deprecation: [@octokit/rest] "number" parameter is deprecated for ".issues.addLabels()". Use "issue_number" instead
9
    at /home/runner/work/_actions/actions/github-script/0.3.0/node_modules/@octokit/rest/plugins/register-endpoints/register-endpoints.js:71:26
10
    at Array.forEach (<anonymous>)
11
    at Object.patchedMethod [as addLabels] (/home/runner/work/_actions/actions/github-script/0.3.0/node_modules/@octokit/rest/plugins/register-endpoints/register-endpoints.js:67:26)
12
    at eval (eval at main (/home/runner/work/_actions/actions/github-script/0.3.0/main.js:19:14), <anonymous>:3:15)
13
    at main (/home/runner/work/_actions/actions/github-script/0.3.0/main.js:20:24)
14
    at Object.<anonymous> (/home/runner/work/_actions/actions/github-script/0.3.0/main.js:5:1)
15
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
17
    at Module.load (internal/modules/cjs/loader.js:641:32)
18
    at Function.Module._load (internal/modules/cjs/loader.js:556:12) {
19
  name: 'Deprecation'
20
}
```

**Comment by jgravois** [comment]
I resolved this by doing:
```js
context.issue_number = context.number
delete context.number
github.issues.addLabels({ ...context.issue })
```

**Comment by jclem** [comment]
Resolved by https://github.com/actions/github-script/commit/1a49f5954551b91e7e3833c74d7be26e4f65406f
