### ISSUE TITLE
Getting RequestError [HttpError]: Not Found on github-script@v4.0.2 while github.issues.update

### ISSUE THREAD

**Issue by degerhz** [actions/github-script#141]
Hi,

I am using the following YAML to create Jira issues when the specific label is added. Then update the GH issue (title enrichment + adding a comment) with Jira issue information.

```
name: Create Jira issue

on:
  issues:
    types: labeled

jobs:
  jira:
    if: ${{ github.event.label.name == 'to-jira' }}
    runs-on: ubuntu-latest
    steps:
      - name: Jira Login
        id: login
        uses: atlassian/gajira-login@v2.0.0
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Create Jira issue
        id: create_jira_issue
        uses: atlassian/gajira-create@v2.0.1
        with:
          project: ABC
          issuetype: Task
          summary: | 
            [GH#${{ github.event.issue.number }}] ${{ github.event.issue.title }}
          description: |
            {panel}
            *Created By:* ${{ github.event.issue.user.login }}
            [Github permalink|${{ github.event.issue.html_url }}]
            {panel}
            ----
            ${{ github.event.issue.body }}
          fields: '{"labels": ["GitHub"]}'

      - name: Update title of GitHub issue
        uses: actions/github-script@v4.0.2
        env:
          JIRA_ISSUE_NUMBER: ${{ steps.create_jira_issue.outputs.issue }}
          GITHUB_ORIGINAL_TITLE: ${{ github.event.issue.title }}
        with:
          github-token: ${{ secrets.JIRA_GITHUB_TOKEN }}
          script: |
            const newTitle = `${process.env.GITHUB_ORIGINAL_TITLE} [${process.env.JIRA_ISSUE_NUMBER}]`
            github.issues.update({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: newTitle
            })

      - name: Add comment to GitHub issue
        uses: actions/github-script@v4.0.2
        with:
          github-token: ${{ secrets.JIRA_GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Internal Jira issue: [${{ steps.create_jira_issue.outputs.issue }}](${{ secrets.JIRA_BASE_URL }}/browse/${{ steps.create_jira_issue.outputs.issue }})'
            })
```

Action is creating the Jira issue successfully, but it fails in `Update title of GitHub issue` step. When I removed that step then it fails in `Add comment to GitHub issue` step. You can see the error below.

```
Run actions/github-script@v4.0.2

RequestError [HttpError]: Not Found
    at /home/runner/work/_actions/actions/github-script/v4.0.2/dist/index.js:2343:23
Error: Unhandled error: HttpError: Not Found
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  name: 'HttpError',
  status: 404,
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
    connection: 'close',
    'content-encoding': 'gzip',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Fri, 30 Apr 2021 14:47:18 GMT',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'transfer-encoding': 'chunked',
    vary: 'Accept-Encoding, Accept, X-Requested-With',
    'x-accepted-oauth-scopes': '',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-media-type': 'github.v3',
    'x-github-request-id': '0741:78EC:36CE517:8515D38:608C1876',
    'x-oauth-scopes': 'public_repo',
    'x-ratelimit-limit': '5000',
    'x-ratelimit-remaining': '4998',
    'x-ratelimit-reset': '1619795701',
    'x-ratelimit-used': '2',
    'x-xss-protection': '0'
  },
  request: {
    method: 'PATCH',
    url: 'https://api.github.com/repos/abc/abc/issues/1',
    headers: {
      accept: 'application/vnd.github.-preview+json',
      'user-agent': 'actions/github-script octokit-core.js/3.2.1 Node.js/12.13.1 (linux; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"title":"New issue [ABC-1]"}',
    request: { agent: [Agent], hook: [Function: bound bound register] }
  },
  documentation_url: 'https://docs.github.com/rest/reference/issues#update-an-issue'
} 
```

Could you please help me to identify the missing or broken part?

Thanks

**Comment by NickLarsenNZ** [comment]
I'm getting the same with:

```yaml
    - name: Create repo if necessary
      uses: actions/github-script@v4
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const repo = await github.repos.get({
            owner: "MyOrg",
            repo: "my-repo",
          });

          console.log(repo);
```

I guess the API has changed?

**Comment by Chaoste** [comment]
Hey, I'm getting the same error with:
```
     - name: approve-and-request-merge
        uses: actions/github-script@v4.1
        with:
          script: |
            github.pulls.createReview({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE',
              body: '@dependabot merge'
            })
          github-token: ${{ secrets.WHYDAH_GITHUB_TOKEN_AUTO_APPROVE }}
```

**Comment by AlexPerathoner** [comment]
Getting same error with:
```yaml

            const artifacts = await github.rest.checks.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              check_run_id: last_run_id,
            });
```

---

According to [this doc](https://docs.github.com/en/rest/overview/troubleshooting?apiVersion=2022-11-28) a `404` is returned when the authentication fails, so I thought it could be an authentication error, and tried:
* custom curl request (so without using this library)
  * using a general token
  * using a fine-grained token
* according to [these docs](https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28) the authorization header should be in the form `Authorization: Bearer <token>`, not `Authorization: token <token>`
  * tried both of the above with Bearer
* using the GitHub CLI, which should theoretically solve authentication issues. However, I still get a `Not found` error.

At this point I have no idea if the url exists and it's an authentication problem, or if it doesn't exist at all.

For context, the curl request:

```curl
curl 'https://api.github.com/repos/AlexPerathoner/SlimHUD/check-runs/3748027294' \    
--header 'X-GitHub-Api-Version: 2022-11-28' \
--header 'authorization: token <token>' \
--header 'Accept: application/vnd.github+json'
```

Note that `https://github.com/AlexPerathoner/SlimHUD/actions/runs/3748260994/` is publicly accessible, and the run definitely exists.

Am I completely missing something?
