### ISSUE TITLE
I am not able to use secrets.GITHUB_TOKEN

### ISSUE THREAD

**Issue by phracek** [actions/github-script#158]
**Describe the bug**
My GitHub actions looks like:
name: CentOS7-tests@TF
```
on:
  issue_comment:
    types:
      - created
jobs:
  pr_commented:
    # This job only runs for '[test]' pull request comments by owner, member
    name: Run tests on Testing Farm service
    runs-on: ubuntu-20.04
    if: |
      github.event.issue.pull_request
      && github.event.comment.body == '[test]'
      && contains(fromJson('["OWNER", "MEMBER"]'), github.event.comment.author_association)
    steps:
      - name: Get pull request number
        id: pr_nr
        run: |
          PR_URL="${{ github.event.comment.issue_url }}"
          echo "::set-output name=PR_NR::${PR_URL##*/}"
      - name: Schedule a test on Testing Farm
        id: sched_test
        run: |
          apt update && apt -y install curl jq
          cat << EOF > request.json
          {
            "api_key": "${{ secrets.TF_PUBLIC_API_KEY }}",
            "test": {"fmf": {
              "url": "https://github.com/phracek/sclorg-testing-farm",
              "ref": "main"
            }},
            "environments": [{
              "arch": "x86_64",
              "os": {"compose": "CentOS-7"},
              "variables": {
                "REPO_URL": "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY",
                "REPO_NAME": "$GITHUB_REPOSITORY",
                "PR_NUMBER": "${{ steps.pr_nr.outputs.PR_NR }}",
                "OS": "centos7"
              }
            }]
          }
          EOF
          curl ${{ secrets.TF_ENDPOINT }}/requests --data @request.json --header "Content-Type: application/json" --output response.json
          echo "::set-output name=REQ_ID::$(jq -r .id response.json)"
          cat response.json
      - name: Add comment with Testing Farm request/result
        # This step adds a new comment to the pull request with a link to the test.

        # TODO: This is a temporary workaround until a proper way to set a commit status is implemented.
        id: comment
        uses: actions/github-script@v4
        if: always()
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Testing Farm - CentOS 7'
            })
```

As soon as the job is trigger, I can see in the actions log
```
SyntaxError: Invalid or unexpected token
Error: Unhandled error: SyntaxError: Invalid or unexpected token
    at new AsyncFunction (<anonymous>)
    at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v4/dist/index.js:2451:56)
    at main (/home/runner/work/_actions/actions/github-script/v4/dist/index.js:2505:26)
    at Module.272 (/home/runner/work/_actions/actions/github-script/v4/dist/index.js:2489:1)
    at __webpack_require__ (/home/runner/work/_actions/actions/github-script/v4/dist/index.js:24:31)
    at startup (/home/runner/work/_actions/actions/github-script/v4/dist/index.js:43:19)
    at /home/runner/work/_actions/actions/github-script/v4/dist/index.js:49:18
    at Object.<anonymous> (/home/runner/work/_actions/actions/github-script/v4/dist/index.js:52:10)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
```

**Comment by phracek** [comment]
Is there any other action that can be used?

If new token, my own e.g, should be created, can you please add to the documentation, how to do it? Thnx

**Comment by joshmgross** [comment]
👋  Hey @phracek,

If you don't specify the `github-token` input, the default `GITHUB_TOKEN` will be used that's available in your workflow

https://docs.github.com/en/actions/reference/authentication-in-a-workflow

Based on the workflow in your issue, that should work for your purposes. I'd recommend removing that line:

```diff
        # TODO: This is a temporary workaround until a proper way to set a commit status is implemented.
        id: comment
        uses: actions/github-script@v4
        if: always()
        with:
-         github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Testing Farm - CentOS 7'
            })
```

If you do need a separate token with different permissions, 
see https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token

**Comment by phracek** [comment]
Closing it. It works now.
