### ISSUE TITLE
Make debugging `SyntaxError` easier

### ISSUE THREAD

**Issue by Marcono1234** [actions/github-script#186]
**Is your feature request related to a problem? Please describe.**
When the script has syntax errors and during parsing a `SyntaxError` is thrown there is no indication at all where in the script the syntax error is:
```
SyntaxError: Unexpected token ';'
    at new AsyncFunction (<anonymous>)
    at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v4.1.0/dist/index.js:3086:56)
    at main (/home/runner/work/_actions/actions/github-script/v4.1.0/dist/index.js:3141:26)
    at Module.272 (/home/runner/work/_actions/actions/github-script/v4.1.0/dist/index.js:3125:1)
    at __webpack_require__ (/home/runner/work/_actions/actions/github-script/v4.1.0/dist/index.js:24:31)
    at startup (/home/runner/work/_actions/actions/github-script/v4.1.0/dist/index.js:43:19)
    at /home/runner/work/_actions/actions/github-script/v4.1.0/dist/index.js:49:18
    at Object.<anonymous> (/home/runner/work/_actions/actions/github-script/v4.1.0/dist/index.js:52:10)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
Error: Unhandled error: SyntaxError: Unexpected token ';'
```
[Workflow run](https://github.com/Marcono1234/github-actions-test/runs/3464171818)
[Workflow file](https://github.com/Marcono1234/github-actions-test/actions/runs/1182978264/workflow)

**Describe the solution you'd like**
Ideally the action should make it easy to detect where the syntax error is.

However, I am not sure if that is possible (though I am not very familiar with Node.js).
StackOverflow questions such as [this](https://stackoverflow.com/q/35252731) and [this](https://stackoverflow.com/q/3526902) do not really have satisfactory (or simple) answers.

**Additional context**
As mentioned in https://github.com/actions/github-script/issues/1#issuecomment-592554672 when a script (without syntax errors) throws an error, the stack trace contains information where in the script the error was thrown.

**Workaround**
Copy the `script` value of the "Run actions/github-script@" group of the workflow run log into your IDE with JavaScript editing support.

**Comment by jclem** [comment]
Unfortunately, there's currently know easy fix for this, since we essentially run your script using `new AsyncFunction(scriptSourceString)`.

I've investigated a few different ways of running scripts that may help with this (writing the script to disk, for example), but they all come with tradeoffs. When I have some time, I'll document the various approaches and put them either in docs or a discussion thread.

In the meantime I'm going to close this issue since due to current limitations it's a `wontfix` for now.

**Comment by hermanbanken** [comment]
Maybe this is helpful: https://stackoverflow.com/questions/35252731/find-details-of-syntaxerror-thrown-by-javascript-new-function-constructor

What about pre-parsing the source code using some compiler, like JSLint?
The current error indeed contains no helpful info:
```
try { new Function(`const foo = .SyntaxErrorHere`)() } catch (e) { console.log(typeof e, Object.getOwnPropertyNames(e), e.stack); }
object [ 'stack', 'message' ] SyntaxError: Unexpected token '.'
    at new Function (<anonymous>)
    at REPL36:1:7
    at Script.runInThisContext (node:vm:129:12)
    at REPLServer.defaultEval (node:repl:562:29)
    at bound (node:domain:421:15)
    at REPLServer.runBound [as eval] (node:domain:432:12)
    at REPLServer.onLine (node:repl:889:10)
    at REPLServer.emit (node:events:402:35)
    at REPLServer.emit (node:domain:475:12)
    at REPLServer.Interface._onLine (node:readline:487:10)
```

Something like this does:
```
const config = { "parserOptions": { "ecmaVersion": 2017 }, "env": { "es6": true } }; // match node version
new Linter().verify(`const foo = .SyntaxErrorHere`,  config);
[
  {
    ruleId: null,
    fatal: true,
    severity: 2,
    message: 'Parsing error: Unexpected token .',
    line: 1,
    column: 13
  }
]
```
