### ISSUE TITLE
Cannot read property 'getWorkflowRun' of undefined

### ISSUE THREAD

**Issue by chenrui333** [actions/github-script#195]
**Describe the bug**
After upgrade to use github-script v5, I have run into the following issue for one of workflows:

```
Error: Unhandled error: TypeError: Cannot read property 'getWorkflowRun' of undefined
    at eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v5/dist/index.js:4942:56), <anonymous>:3:39)
    at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v5/dist/index.js:4943:12)
    at main (/home/runner/work/_actions/actions/github-script/v5/dist/index.js:4997:26)
    at Module.272 (/home/runner/work/_actions/actions/github-script/v5/dist/index.js:4981:1)
    at __webpack_require__ (/home/runner/work/_actions/actions/github-script/v5/dist/index.js:24:31)
    at startup (/home/runner/work/_actions/actions/github-script/v5/dist/index.js:43:19)
    at /home/runner/work/_actions/actions/github-script/v5/dist/index.js:49:18
    at Object.<anonymous> (/home/runner/work/_actions/actions/github-script/v5/dist/index.js:52:10)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
```

**Comment by chenrui333** [comment]
Per [this doc](https://github.com/actions/github-script/#breaking-changes-in-v5), `github.actions.getWorkflowRun` becomes `github.rest.actions.getWorkflowRun`
