### ISSUE TITLE
createWorkflowDispatch failed 

### ISSUE THREAD

**Issue by liya2017** [actions/github-script#298]
**Describe the bug**
Got the error like 
``` 
Unhandled error: HttpError: Resource not accessible by integration
    at /home/runner/work/_actions/actions/github-script/v6/dist/index.js:6173:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:13340:16), <anonymous>:84:16)
    at async main (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:13436:20) {
  status: 403,
```
The js worked for me before, just get the error this week. 

**To Reproduce**
1. create a github app
2. get the app Id and secret
3. a workflow step that using Generate  bot token with app Id and secret
4. next step is using actions/github-script@v6 to  createWorkflowDispatch with token that generated by step 3.

**Expected behavior**
a workflow can be triggered by dispatch event

below is my workflow yaml:
```
jobs:
  test:
    name: from-comments
    runs-on: ubuntu-20.04
    steps:
      - name: Generate axon-bot token
        id: generate_bot_token
        uses: wow-actions/use-app-token@v1
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}
      - uses: actions/checkout@v3
      - name: Dispatch ci if user does have correct permission
        id: dispatch
        uses: actions/github-script@v6
        with:
          github-token: ${{ steps.generate_bot_token.outputs.token }}
          script: |
            const dispatch = {
              comment_body: `${{ github.event.comment.body }}`,
              repo: context.repo,
              issue: context.issue,
            };
            const jsonDispatch = JSON.stringify(dispatch)
              .replace(/\\b/g, "\\\\b")
              .replace(/\\f/g, "\\\\f")
              .replace(/\\n/g, "\\\\n")
              .replace(/\\r/g, "\\\\r")
              .replace(/\\t/g, "\\\\t");
            
            // get pr comments body,not issue comments body
            const pr = 
             await github.rest.pulls.get({
               owner: context.repo.owner,
               repo: context.repo.repo,
               pull_number: context.issue.number,
            });
         
              const resp = await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "fmt.yml",
              ref: "main",
              inputs: {
                dispatch: jsonDispatch,
              }
              });
              core.info(`${JSON.stringify(resp, null, 2)}`);
              }

```

**Comment by liya2017** [comment]
the issue fixed by app permissions

**Comment by brianjmurrell** [comment]
> the issue fixed by app permissions

Can you expand on this?  I am seeing this same kind of result:

```
RequestError [HttpError]: Resource not accessible by integration
    at /data/gha_runners/actions-runner2/_work/_actions/actions/github-script/v6/dist/index.js:6172:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async eval (eval at callAsyncFunction (/data/gha_runners/actions-runner2/_work/_actions/actions/github-script/v6/dist/index.js:13356:16), <anonymous>:3:16)
    at async main (/data/gha_runners/actions-runner2/_work/_actions/actions/github-script/v6/dist/index.js:13452:20) {
  status: 403,
...
```

from a fairly simple step:

```yaml
      - name: Test
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const result = await github.rest.actions.createWorkflowDispatch({
              owner: 'foo',
              repo: 'bar',
              workflow_id: 'test.yml',
              ref: 'foo/gha-test'
            })
            console.log(result)
```

The items worthy of noting are that the above is being run from a different repo than _bar_ but in the same organization (_foo_) and that the `test.yml` workflow only exists on the _foo/gha_test_  branch and not the default branch in _foo/bar_.  But I am using that as my `ref:` as you can see.

**Comment by liya2017** [comment]
> ```yaml
>       - name: Test
>         uses: actions/github-script@v6
>         with:
>           github-token: ${{ secrets.GITHUB_TOKEN }}
>           script: |
>             const result = await github.rest.actions.createWorkflowDispatch({
>               owner: 'foo',
>               repo: 'bar',
>               workflow_id: 'test.yml',
>               ref: 'foo/gha-test'
>             })
>             console.log(result)
> ```

Maybe you need check your token access permissions，should be read and write access for workflow
