### ISSUE TITLE
Preview flash is not accepted when using ant-man and creating a deployment status

### ISSUE THREAD

**Issue by localheinz** [actions/github-script#32]
Not entirely sure if this is related to this repository, but I'm having issues switching from `octokit/request-action` to `actions/github-script`.

In my workflow, I create a deployment using [`chrnorm/deployment-action`](https://github.com/chrnorm/deployment-action).

This works fine.

### `octokit/request-action`

In a following step, when the actual deployment fails, I mark the deployment as failure using [`octokit/request-action`](https://github.com/octokit/request-action).

```yaml
- name: "Mark deployment as success"
  if: "failure()"
  uses: "octokit/request-action@v2.0.0"
  with:
    auto_inactive: false
    deployment_id: "${{ steps.create-deployment.outputs.deployment_id }}"
    environment: "master"
    environment_url: "https://localheinz.com"
    owner: "localheinz"
    repo: "localheinz.com"
    repository: "${{ github.repository }}"
    route: "POST /repos/:owner/:repo/deployments/:deployment_id/statuses"
    state: "success"
  env:
    GITHUB_TOKEN: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"
```

This works fine.

### `actions/github-script`

Now, because I find that [`actions/github-script`](https://github.com/actions/github-script) gives me more flexibility, I have switched to using it:

```diff
 - name: "Mark deployment as success"
   if: "failure()"
-  uses: "octokit/request-action@v2.0.0"
+  uses: "actions/github-script@0.8.0"
   with:
-    auto_inactive: false
-    deployment_id: "${{ steps.create-deployment.outputs.deployment_id }}"
-    environment: "master"
-    environment_url: "https://localheinz.com"
-    owner: "localheinz"
-    repo: "localheinz.com"
-    repository: "${{ github.repository }}"
-    route: "POST /repos/:owner/:repo/deployments/:deployment_id/statuses"
-    state: "success"
-  env:
-    GITHUB_TOKEN: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"
+    github-token: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"
+    script: |
+      github.repos.createDeploymentStatus({
+        auto_inactive: false,
+        deployment_id: "${{ steps.create-deployment.outputs.deployment_id }}",
+        environment: "master",
+        environment_url: "https://localheinz.com",
+        mediaType: {
+          previews: [
+            "ant-man",
+            "flash"
+          ]
+        },
+        owner: context.repo.owner,
+        repo: context.repo.repo,
+        state: "success"
+      })
```

As you can see, I have provided the media types using the `mediaType` property

- `ant-man`, required for using the `environment` parameter
- `flash`, required for using the `environment_url` parameter

as documented at

- [Deployments | GitHub Developer Guide](https://developer.github.com/v3/repos/deployments/#create-a-deployment-status)
- [Previews | octokit/rest.js](https://octokit.github.io/rest.js/v17#previews)

This fails with `Invalid value for parameter 'environment': "master"` as you can see here:

```
2020-03-19T21:56:26.6439099Z ##[group]Run actions/github-script@0.8.0
2020-03-19T21:56:26.6439589Z with:
2020-03-19T21:56:26.6440555Z   github-token: ***
2020-03-19T21:56:26.6441745Z   script: github.repos.createDeploymentStatus({
  auto_inactive: true,
  deployment_id: "1234567890",
  environment: "master",
  environment_url: "https://localheinz.com",
  mediaType: {
    previews: [
      "ant-man",
      "flash"
    ]
  },
  owner: context.repo.owner,
  repo: context.repo.repo,
  state: "success"
})

2020-03-19T21:56:26.6442704Z   debug: false
2020-03-19T21:56:26.6443342Z   user-agent: actions/github-script
2020-03-19T21:56:26.6443720Z   result-encoding: json
2020-03-19T21:56:26.6446531Z ##[endgroup]
2020-03-19T21:56:26.7568708Z RequestError [HttpError]: Invalid value for parameter 'environment': "master"
2020-03-19T21:56:26.7569775Z     at /home/runner/work/_actions/actions/github-script/0.8.0/dist/index.js:4278:15
2020-03-19T21:56:26.7570432Z     at Array.forEach (<anonymous>)
2020-03-19T21:56:26.7571280Z     at /home/runner/work/_actions/actions/github-script/0.8.0/dist/index.js:4216:12
2020-03-19T21:56:26.7571799Z     at Array.forEach (<anonymous>)
2020-03-19T21:56:26.7572517Z     at validate (/home/runner/work/_actions/actions/github-script/0.8.0/dist/index.js:4189:23) {
2020-03-19T21:56:26.7573221Z   name: 'HttpError',
2020-03-19T21:56:26.7573630Z   status: 400,
2020-03-19T21:56:26.7574114Z   headers: {},
2020-03-19T21:56:26.7574562Z   request: {
2020-03-19T21:56:26.7575193Z     method: 'POST',
2020-03-19T21:56:26.7575947Z     baseUrl: 'https://api.github.com',
2020-03-19T21:56:26.7576393Z     headers: {
2020-03-19T21:56:26.7577003Z       accept: 'application/vnd.github.v3+json',
2020-03-19T21:56:26.7577752Z       'user-agent': 'actions/github-script octokit.js/16.43.1 Node.js/12.13.1 (Linux 5.0; x64)'
2020-03-19T21:56:26.7578279Z     },
2020-03-19T21:56:26.7578887Z     mediaType: { format: '', previews: [Array] },
2020-03-19T21:56:26.7579372Z     request: { hook: [Function: bound bound register], validate: [Object] },
2020-03-19T21:56:26.7580095Z     url: '/repos/:owner/:repo/deployments/:deployment_id/statuses',
2020-03-19T21:56:26.7580573Z     auto_inactive: true,
2020-03-19T21:56:26.7580998Z     deployment_id: 1234567890,
2020-03-19T21:56:26.7581574Z     environment: 'master',
2020-03-19T21:56:26.7582190Z     environment_url: 'https://localheinz.com',
2020-03-19T21:56:26.7582805Z     owner: 'localheinz',
2020-03-19T21:56:26.7583362Z     repo: 'localheinz.com',
2020-03-19T21:56:26.7583923Z     state: 'success'
2020-03-19T21:56:26.7584340Z   }
2020-03-19T21:56:26.7584730Z }
2020-03-19T21:56:26.7591748Z ##[error]Invalid value for parameter 'environment': "master"
```

As an alternative, I have tried using the `previews` attribute

```diff
   with:
     debug: true
     github-token: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"
+    previews: "ant-man,flash"
     script: |
       github.repos.createDeploymentStatus({
         auto_inactive: false,
         deployment_id: "${{ steps.create-deployment.outputs.deployment_id }}",
         environment: "master",
         environment_url: "https://localheinz.com",
-        mediaType: {
-          previews: [
-            "ant-man",
-            "flash"
-          ]
-        },
         owner: context.repo.owner,
         repo: context.repo.repo,
         state: "success"
```

as documented in [`action.yml`](https://github.com/actions/github-script/blob/80a5e943b446817466ff17e8b61cb80848641ed6/action.yml#L21-L22).

This again fails with `Invalid value for parameter 'environment': "master"` as you can see here:

```
2020-03-19T22:43:32.3037918Z ##[group]Run actions/github-script@0.8.0
2020-03-19T22:43:32.3038353Z with:
2020-03-19T22:43:32.3039328Z   github-token: ***
2020-03-19T22:43:32.3039768Z   previews: ant-man,flash
2020-03-19T22:43:32.3040472Z   script: github.repos.createDeploymentStatus({
  auto_inactive: true,
  deployment_id: "1234567890",
  environment: "master",
  environment_url: "https://localheinz.com",
  owner: context.repo.owner,
  repo: context.repo.repo,
  state: "success"
})

2020-03-19T22:43:32.3041664Z   debug: false
2020-03-19T22:43:32.3042094Z   user-agent: actions/github-script
2020-03-19T22:43:32.3042535Z   result-encoding: json
2020-03-19T22:43:32.3044720Z ##[endgroup]
2020-03-19T22:43:32.4054392Z RequestError [HttpError]: Invalid value for parameter 'environment': "master"
2020-03-19T22:43:32.4055596Z     at /home/runner/work/_actions/actions/github-script/0.8.0/dist/index.js:4278:15
2020-03-19T22:43:32.4056521Z     at Array.forEach (<anonymous>)
2020-03-19T22:43:32.4058571Z ##[error]Invalid value for parameter 'environment': "master"
2020-03-19T22:43:32.4062517Z     at /home/runner/work/_actions/actions/github-script/0.8.0/dist/index.js:4216:12
2020-03-19T22:43:32.4063169Z     at Array.forEach (<anonymous>)
2020-03-19T22:43:32.4063984Z     at validate (/home/runner/work/_actions/actions/github-script/0.8.0/dist/index.js:4189:23) {
2020-03-19T22:43:32.4064806Z   name: 'HttpError',
2020-03-19T22:43:32.4065332Z   status: 400,
2020-03-19T22:43:32.4065838Z   headers: {},
2020-03-19T22:43:32.4066321Z   request: {
2020-03-19T22:43:32.4066970Z     method: 'POST',
2020-03-19T22:43:32.4067767Z     baseUrl: 'https://api.github.com',
2020-03-19T22:43:32.4068460Z     headers: {
2020-03-19T22:43:32.4069222Z       accept: 'application/vnd.github.v3+json',
2020-03-19T22:43:32.4070019Z       'user-agent': 'actions/github-script octokit.js/16.43.1 Node.js/12.13.1 (Linux 5.0; x64)'
2020-03-19T22:43:32.4070601Z     },
2020-03-19T22:43:32.4071242Z     mediaType: { format: '', previews: [Array] },
2020-03-19T22:43:32.4072010Z     request: { hook: [Function: bound bound register], validate: [Object] },
2020-03-19T22:43:32.4072815Z     url: '/repos/:owner/:repo/deployments/:deployment_id/statuses',
2020-03-19T22:43:32.4073381Z     auto_inactive: true,
2020-03-19T22:43:32.4073897Z     deployment_id: 210675589,
2020-03-19T22:43:32.4074870Z     environment: 'master',
2020-03-19T22:43:32.4075610Z     environment_url: 'https://localheinz.com',
2020-03-19T22:43:32.4076305Z     owner: 'localheinz',
2020-03-19T22:43:32.4076957Z     repo: 'localheinz.com',
2020-03-19T22:43:32.4077636Z     state: 'success'
2020-03-19T22:43:32.4078155Z   }
2020-03-19T22:43:32.4078756Z }
```

Now, when I remove the `environment` parameter and assume the environment that was used when creating the deployment in the first place:

```diff
   with:
     debug: true
     github-token: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"
-    previews: "ant-man,flash"
+    previews: "ant-man"
     script: |
       github.repos.createDeploymentStatus({
         auto_inactive: false,
         deployment_id: "${{ steps.create-deployment.outputs.deployment_id }}",
-        environment: "master",
         environment_url: "https://localheinz.com",
         owner: context.repo.owner,
         repo: context.repo.repo,
```

this works fine.

## Question

Why does the original request work with `octokit/request-action`, but not with `actions/github-script`?

**Comment by localheinz** [comment]
Looks like the documentation is outdated.

🤷‍♂
