### ISSUE TITLE
401 Error running API call through github-script

### ISSUE THREAD

**Issue by fiddlermikey** [actions/github-script#324]
I am getting 401 “Bad Credentials” trying to run some api calls through github-script. This was working on Monday (Jan 9) but stopped working on Tuesday (Jan 10)

I have contacted GitHub Support and they have been able to reproduce the error. They say it is most likely due to the 3rd party action, "github-script" (6.3.3) causing this issue.
https://support.github.com/ticket/enterprise/15636/1960901

Steps to reproduce

1.     Create PAT with Admin access (r/w) to repos and org/teams
2.     Set an Org secret using the value from my PAT
3.     Run the workflow manually (or from a push)
4.     Failure with 401 error

Expected to produce a list of repositories
I have pared down the workflow to isolate the issue. Attached is the workflow ([list-repo-status.yml](https://github.zendesk.com/attachments/token/4dgmX0y4xCH14JKZAIbtmCqHK/?name=list-repo-status.yml)) and the debug log
list-repo-status.yml
[list-repo-status.debug.log.txt](https://github.zendesk.com/attachments/token/SIVI58CUWh4hXwgwkH7Qd8c7Z/?name=list-repo-status.debug.log.txt)

Last successful run can be found: 
https://github.com/teamkfinteg/reportscripts/actions/runs/3878744215

First failure (only difference was trying to replace trigger with cron
https://github.com/teamkfinteg/reportscripts/actions/runs/3885379831

I used Postman with the same token to test and it works as expected.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Firefox 
 - Version: 108.0.2 (64-bit)

**Comment by fiddlermikey** [comment]
I tried specifying v6.3.2 and the sha 0306a3c1de9987bfd34b47af6926b0e96e399e2 
Both attempts failed with the same error.

**Comment by joshmgross** [comment]
👋 @fiddlermikey, this action is a thin wrapper around Octokit and the GitHub API. The action itself isn't modifying that token or doing anything differently from an authentication perspective.

Are you able to use the same token on your local machine to call that REST API?

https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#list-organization-repositories

You can use `curl` or the gh CLI with your token:

```
curl \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer <YOUR-TOKEN>"\
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/orgs/ORG/repos
```

```
# GitHub CLI api
# https://cli.github.com/manual/gh_api

gh api \
  -H "Accept: application/vnd.github+json" \
  /orgs/ORG/repos
```

**Comment by INRIX-Iurii-Okhmat** [comment]
@joshmgross I've got the same issue going on, but I've never used `github-script` before so I might be doing something wrong. 

I've got:
- PAT, defined in repository secrets
- Workflow step that should query repos by topic:

```yaml
      - name: List repositories
        uses: actions/github-script@v6
        id: repos
        with:
          result-encoding: json
          github-token: ${ secrets.PAT_TOKEN }
          script: |
            const res = await github.rest.search.repos({
              q: 'my-topic in:topics archived:false'
            });

            const repos = (res.data.items || []).map(repo => ({
              id: repo.id,
              name: repo.name,
              owner: repo.owner.login,
              topics: repo.topics || []
            }));

            return repos;
```

- PAT works - both using `curl` and `"octokit": "^2.0.14"` NPM package
- Running with `act` fails
- Running on Github fails as well 

```text
Run actions/github-script@v6
  
RequestError [HttpError]: Bad credentials
    at /home/runner/work/_actions/actions/github-script/v6/dist/index.js:6803:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:15099:16), <anonymous>:3:13)
    at async main (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:15198:20) {
  status: 401,
  response: {
    url: 'https://api.github.com/search/repositories?q=my-topic%20in%3Atopics%20archived%3Afalse',
    status: 401,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      connection: 'close',
      'content-length': '80',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Thu, 02 Mar 20[23](...../actions/runs/4310595832/jobs/7519186897#step:5:24) 04:30:38 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-media-type': 'github.v3',
      'x-github-request-id': 'D742:6C6A:46F7CD0:493DEA3:6400[26](...../actions/runs/4310595832/jobs/7519186897#step:5:27)6E',
      'x-ratelimit-limit': '10',
      'x-ratelimit-remaining': '9',
      'x-ratelimit-reset': '1677731498',
      'x-ratelimit-resource': 'search',
      'x-ratelimit-used': '1',
      'x-xss-protection': '0'
    },
    data: {
      message: 'Bad credentials',
      documentation_url: 'https://docs.github.com/rest'
    }
  },
  request: {
    method: 'GET',
    url: 'https://api.github.com/search/repositories?q=my-topic%20in%3Atopics%20archived%3Afalse',
    headers: {
      accept: 'application/vnd.github.-preview+json',
      'user-agent': 'actions/github-script octokit-core.js/3.6.0 Node.js/16.16.0 (linux; x64)',
      authorization: 'token [REDACTED]'
    },
    request: { agent: [Agent], hook: [Function: bound bound register] }
  }
}
```

**Comment by midalias** [comment]
@fiddlermikey,

I found this issue while googling the same error message. Note that I am using the GH API not https://github.com/actions/github-script. The cause of the error was a space between $ and {{. Perhaps in your case it is something similar.

```shell
GITHUB_TOKEN: $ {{ secrets.GH_API_SCAN }}
```
