### ISSUE TITLE
"github.rest.actions.merge" throws an error

### ISSUE THREAD

**Issue by vkurenyshev-godaddy** [actions/github-script#378]
**Describe the bug**
I am trying to use `github.rest.actions.merge` in my GH Actions workflow but getting an error
```
TypeError: github.rest.actions.merge is not a function
```

I am trying to understand what I am missing.
I checked for documentation in https://octokit.github.io/rest.js/v19#repos-merge. 
My guess that this should be called `github.rest.actions.merge`. Another action `github.rest.actions.createWorkflowDispatch` is working fine.

The full error output is
```
Run actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410
TypeError: github.rest.actions.merge is not a function
    at eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/d7906e4ad0b1822421a7e6a35d5ca353c962f410/dist/index.js:15143:[16](https://github.com/gdcorp-registry/unicorn-actions-playground/actions/runs/4856773328/jobs/8656664763#step:2:17)), <anonymous>:3:21)
    at callAsyncFunction (/home/runner/work/_actions/actions/github-script/d7906e4ad0b1822421a7e6a35d5ca353c962f410/dist/index.js:15144:12)
    at main (/home/runner/work/_actions/actions/github-script/d7906e4ad0b1822421a7e6a35d5ca353c962f410/dist/index.js:15236:26)
    at /home/runner/work/_actions/actions/github-script/d7906e4ad0b1822421a7e6a35d5ca353c962f410/dist/index.js:152[17](https://github.com/gdcorp-registry/unicorn-actions-playground/actions/runs/4856773328/jobs/8656664763#step:2:18):1
    at /home/runner/work/_actions/actions/github-script/d7906e4ad0b[18](https://github.com/gdcorp-registry/unicorn-actions-playground/actions/runs/4856773328/jobs/8656664763#step:2:19)224[21](https://github.com/gdcorp-registry/unicorn-actions-playground/actions/runs/4856773328/jobs/8656664763#step:2:22)a7e6a35d5ca353c962f410/dist/index.js:15268:3
    at Object.<anonymous> (/home/runner/work/_actions/actions/github-script/d7906e4ad0b18[22](https://github.com/gdcorp-registry/unicorn-actions-playground/actions/runs/4856773328/jobs/8656664763#step:2:23)421a7e6a35d5ca353c962f410/dist/index.js:15271:12)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
Error: Unhandled error: TypeError: github.rest.actions.merge is not a function
```

**To Reproduce**
Configure a workflow like this
```
  Merge-Main-to-TEST:
    runs-on: ubuntu-latest
    steps:
      - name: Merge branches 'main' -> 'TEST'
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
        with:
          script: |
            github.rest.actions.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: 'main',
              base: 'TEST'
            })
```

**Expected behavior**
GH Action will merge code from branch `main` to branch `TEST`

**Desktop (please complete the following information):**
Unrelated. The error is with GH Actions.

**Smartphone (please complete the following information):**
Unrelated. The error is with GH Actions.

Please advise what I am doing wrong :)

**Comment by vkurenyshev-godaddy** [comment]
Thank you @joshmgross for you time, it is working. Not sure how I missed that.
